services:
  dns-server-2:
    build:
      context: ..
      dockerfile: dns.Dockerfile
    container_name: dns-dck-dns2
    ports:
     # systemctl stop systemd-resolved
     # systemctl disable systemd-resolved
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./etc/bind:/etc/bind:rw